### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by Anurag5086** [Anurag5086/chatify#1]
Update Readme
Add Contributing Guidelines
Add license

**Comment by dgabriel123** [comment]
Hello, may I work on this?

**Comment by Anurag5086** [comment]
> Hello, may I work on this?

@dgabriel123 Go Ahead! :)

**Comment by dgabriel123** [comment]
> > Hello, may I work on this?
> 
> @dgabriel123 Go Ahead! :)

Just to clarify: MIT license?

**Comment by Anurag5086** [comment]
> > > Hello, may I work on this?
> > 
> > 
> > @dgabriel123 Go Ahead! :)
> 
> Just to clarify: MIT license?

Yes!

**Comment by dgabriel123** [comment]
> > > > Hello, may I work on this?
> > > 
> > > 
> > > @dgabriel123 Go Ahead! :)
> > 
> > 
> > Just to clarify: MIT license?
> 
> Yes!

I plan to make a fairly short and simple CONTRIBUTING doc. Is there anything specifically that you would like me to add in addition to the standard generic stuff?

**Comment by Anurag5086** [comment]
> > > > > Hello, may I work on this?
> > > > 
> > > > 
> > > > @dgabriel123 Go Ahead! :)
> > > 
> > > 
> > > Just to clarify: MIT license?
> > 
> > 
> > Yes!
> 
> I plan to make a fairly short and simple CONTRIBUTING doc. Is there anything specifically that you would like me to add in addition to the standard generic stuff?

Just make a PR, ill let you know after that.

**Comment by dgabriel123** [comment]
@Anurag5086 anything else you'd like to have added to either doc?

**Comment by Anurag5086** [comment]
@dgabriel123 Its cool Thanks!
